# Deploy Container Watchtower

- name: Create Directory
  file:
    path: /docker/watchtower
    state: directory
    group: docker

- name: Copy watchtower
  copy:
    src: "docker-compose.yml"
    dest: "/docker/watchtower"
    mode: 0664
    group: docker
    force: yes

- name: Start Watchtower
  shell: "docker-compose down && docker-compose pull && docker-compose up -d"
  args:
    chdir: /docker/watchtower
