version: '3'

services:
  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower
    restart: always
    command: --schedule "0 0 3 * * 1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=
      - WATCHTOWER_NOTIFICATIONS_LEVEL=error
      - WATCHTOWER_CLEANUP=true
